server:
  port: 8080
security:
  basic:
    enabled: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sup-activiti?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password: wonders,1
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  devtools:
    restart:
      enabled: true  #设置开启热部署
      #additional-paths: src/main/java #重启目录
      #exclude: WEB-INF/**
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效